### ISSUE TITLE
The request is returning RequestId and MessageId but the message is not going

### ISSUE THREAD

**Issue by SoumyoNawab8** [Sean-Bradley/AWS-SNS-SMS-with-NodeJS#3]
On checking with AWS SNS-> Text messaging Dashboard logs I can see that it failed.
I have sent the mobile number like this +917xxxxxxxxx.
Any idea what I am missing though?

**Comment by cancerian-geek** [comment]
I am also facing the same issue from past two days someone please help

**Comment by SoumyoNawab8** [comment]
> I am also facing the same issue from past two days someone please help

I got that resolved by contacting aws support team my account actually lacked SNS quota that is the reason I was facing that issue.
